apiVersion: v1
kind: Service
metadata:
  name: emailer-service
  labels:
    app: emailer
spec:
  selector:
    app: emailer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

